default: &default
  enabled: true
  abbreviation: "awri"
  short_name: "Australian Wine Research Institute"
  long_name: "Australian Wine Research Institute"
  publisher_id: grid.452839.1
  ror_ids:
    - https://ror.org/0569vjj73
  tenant_id: awri
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: ip_address
    ranges: [ "129.127.182.188", "129.127.182.166" ]
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]
