default: &default
  enabled: true
  abbreviation: "awri"
  short_name: "Australian Wine Research Institute"
  long_name: "Australian Wine Research Institute"
  publisher_id: grid.452839.1
  ror_ids:
    - https://ror.org/0569vjj73
  tenant_id: awri
  authentication:
    strategy: ip_address
    ranges: [ "129.127.182.188", "129.127.182.166" ]
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
