default: &default
  enabled: true
  abbreviation: "CCS-TCCS"
  short_name: "Claremont College Services (TCCS)"
  long_name: "Claremont College Services (TCCS)"
  publisher_id: grid.431610.1
  ror_ids:
    - https://ror.org/03xaz7s88
    - https://ror.org/0157pnt69
    - https://ror.org/04n1me355
    - https://ror.org/025ecfn45
    - https://ror.org/00f4jdp82
    - https://ror.org/0197n2v40
    - https://ror.org/0074grg94
    - https://ror.org/00p55jd14
    - https://ror.org/01n260e81
  tenant_id: clare-cs
  authentication:
    strategy: shibboleth
    entity_id: https://webauth.cuc.claremont.edu/idp/shibboleth
    entity_domain: webauth.cuc.claremont.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
