default: &default
  enabled: true
  abbreviation: "HMC"
  short_name: "Harvey Mudd College"
  long_name: "Harvey Mudd College"
  publisher_id: grid.256859.5
  ror_ids:
    - https://ror.org/025ecfn45
  tenant_id: clare-hmc
  authentication:
    strategy: shibboleth
    entity_id: https://identity.hmc.edu/idp
    entity_domain: hmc.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true
  sponsor_id: clare-cs

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here
