default: &default
  enabled: true
  abbreviation: "Pitzer"
  short_name: "Pitzer College"
  long_name: "Pitzer College"
  publisher_id: grid.418658.6
  ror_ids:
    - https://ror.org/0197n2v40
  tenant_id: clare-pitzer
  authentication:
    strategy: shibboleth
    entity_id: https://webauth.pitzer.edu/idp/shibboleth
    entity_domain: pitzer.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true
  sponsor_id: clare-cs

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
