default: &default
  enabled: true
  abbreviation: "CMC"
  short_name: "Claremont McKenna College"
  long_name: "Claremont McKenna College"
  publisher_id: grid.254272.4
  ror_ids:
    - https://ror.org/04n1me355
  tenant_id: clare-cmc
  authentication:
    strategy: shibboleth
    entity_id: https://webauth.cmc.edu/idp/shibboleth
    entity_domain: webauth.cmc.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true
  sponsor_id: clare-cs

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

