default: &default
  enabled: true
  abbreviation: "Scripps College"
  short_name: "Scripps College"
  long_name: "Scripps College"
  publisher_id: grid.421979.0
  ror_ids:
    - https://ror.org/00p55jd14
  tenant_id: clare-scripps
  authentication:
    strategy: shibboleth
    entity_id: https://webauth.scrippscollege.edu/idp/shibboleth
    entity_domain: scrippscollege.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true
  sponsor_id: clare-cs

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
