default: &default
  enabled: true
  abbreviation: "colostate"
  short_name: "Colorado State University"
  long_name: "Colorado State University"
  publisher_id: grid.47894.36
  ror_ids:
    - https://ror.org/03k1gpj17
  tenant_id: colostate
  authentication:
    strategy: shibboleth
    entity_id: https://shibidp.colostate.edu/idp/shibboleth
    entity_domain: colostate.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]
