default: &default
  enabled: true
  abbreviation: "Columbia"
  short_name: "Columbia University"
  long_name: "Columbia University in the City of New York"
  publisher_id: grid.21729.3f
  ror_ids:
    - https://ror.org/00hj8s172
    - https://ror.org/01esghr10
  tenant_id: columbia
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:columbia.edu
    entity_domain: columbia.edu
  default_license: cc0
  campus_contacts: ["jt2118@columbia.edu"]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false

test:
  <<: *default
  #Add any items that need to override the defaults here
