default: &default
  enabled: true
  abbreviation: "CSUEB"
  short_name: "Cal State East Bay"
  long_name: "California State University, East Bay"
  publisher_id: grid.253557.3
  ror_ids:
    - https://ror.org/04jaeba88
  tenant_id: csueb
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: https://vince.csueastbay.edu/idp/shibboleth
    entity_domain: vince.csueastbay.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]

