# I think we need to keep UC Press and DataONE (but disabled) for the DOI metadata update info in here
default: &default
  enabled: false
  abbreviation: "DataONE"
  short_name: "DataONE"
  long_name: "DataONE"
  publisher_id: isni:0000000404085195
  # DataONE doesn't have a ROR that I could find and it is more or less obsolete except legacy datasets
  ror_ids:
    - https://ror.org/00xDaTaONE-FIXME
  tenant_id: dataone
  authentication:
    strategy: none
  default_license: cc0
  dash_logo_after_tenant: false
  campus_contacts: ["scott.fisher@ucop.edu"]
  data_deposit_agreement: false
  partner_display: false
  covers_dps: true

development:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

demo:
  <<: *default

production:
  <<: *default
  manager_email: [""]
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
