default: &default
  enabled: true
  abbreviation: "DRI"
  short_name: "Desert Research Institute"
  long_name: "Desert Research Institute"
  publisher_id: grid.474431.1
  ror_ids:
    - https://ror.org/02vg22c33
  tenant_id: dri
  authentication:
    strategy: shibboleth
    entity_id: http://www.okta.com/exkh1l6ocbKBRm4RB1t7
    entity_domain: www.okta.com
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  authentication:
    strategy: shibboleth
    entity_id: http://www.okta.com/exkh1l6ocbKBRm4RB1t7
    entity_domain: www.okta.com
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
