default: &default
  enabled: true
  abbreviation: "dryad_ip"
  short_name: "Dryad IP Address Test"
  long_name: "Dryad Data Platform IP Address Test"
  publisher_id: isni:0000000446638050
  ror_ids:
    - https://ror.org/dummy
  tenant_id: dryad_ip
  authentication:
    strategy: ip_address
    ranges: ["128.48.67.15/255.255.255.0", "127.0.0.1/255.255.255.0"]
  default_license: cc0
  campus_contacts: ["ryan@datadryad.org"] # for testing
  data_deposit_agreement: false
  partner_display: false
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here
  partner_display: true

local_dev:
  <<: *DEVELOPMENT

aws_db:
  <<: *default

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[:production][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[:production][:merritt_dryad_password] %>

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
