default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "dryad_ip"
  short_name: "Dryad IP Address Test"
  long_name: "Dryad Data Platform IP Address Test"
  publisher_id: isni:0000000446638050
  ror_ids:
    - https://ror.org/dummy
  tenant_id: dryad_ip
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: ip_address
    ranges: ["128.48.67.15/255.255.255.0", "127.0.0.1/255.255.255.0"]
  default_license: cc0
  campus_contacts: ["scott.fisher@ucop.edu"] # for testing
  data_deposit_agreement: false
  partner_display: false
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here
  partner_display: true


local_dev:
  <<: *DEVELOPMENT

aws_db:
  <<: *default

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %>

migration:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[:production][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[:production][:merritt_dryad_password] %>

production:
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_password] %>
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]


