default: &default
  enabled: false
  abbreviation: "IITISM"
  short_name: "Indian Institute of Technology Dhanbad"
  long_name: "Indian Institute of Technology Dhanbad"
  publisher_id: grid.417984.7
  ror_ids:
    - https://ror.org/013v3cc28
  tenant_id: iitism
  authentication:
    strategy: shibboleth
    entity_id: https://idp.iitism.ac.in/idp/shibboleth               
    entity_domain: idp.iitism.ac.in
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: false
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
