default: &default
  enabled: true
  abbreviation: "KAUST"
  short_name: "King Abdullah University of Science and Technology"
  long_name: "King Abdullah University of Science and Technology"
  publisher_id: grid.45672.32
  ror_ids:
    - https://ror.org/01q3tbs38
    - https://ror.org/02f6hdc06
    - https://ror.org/00qd31w11
  tenant_id: kaust
  authentication:
    strategy: shibboleth
    entity_id: https://waseet.kaust.edu.sa/idp/shibboleth
    entity_domain: waseet.kaust.edu.sa
  default_license: cc0
  campus_contacts: []
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: []

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
