default: &default
  enabled: true
  abbreviation: "kyotou"
  short_name: "Kyoto University"
  long_name: "Kyoto University"
  publisher_id: grid.258799.8
  ror_ids:
    - https://ror.org/02kpeqv85
    - https://ror.org/05gwbwn20
    - https://ror.org/05qs31q25
  tenant_id: kyotou
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: https://authidp2.iimc.kyoto-u.ac.jp/idp/shibboleth
    entity_domain: authidp2.iimc.kyoto-u.ac.jp
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  authentication:
    strategy: shibboleth
    entity_id: https://authidp1.iimc.kyoto-u.ac.jp/idp/shibboleth
    entity_domain: authidp1.iimc.kyoto-u.ac.jp
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]
