default: &default
  enabled: true
  abbreviation: "LBNL"
  short_name: "Lawrence Berkeley Lab"
  long_name: "Lawrence Berkeley National Laboratory"
  publisher_id: grid.184769.5
  ror_ids:
    - https://ror.org/02jbv0t02
  tenant_id: lbnl
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:lbl.gov
    entity_domain: datasets2-dev.lbl.gov
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  enabled: true
  identifier_service:
    provider: ezid
    shoulder: "doi:10.7941/D1"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  campus_contacts: [""]
