default: &default
  enabled: true
  abbreviation: "LBNL"
  short_name: "Lawrence Berkeley Lab"
  long_name: "Lawrence Berkeley National Laboratory"
  publisher_id: grid.184769.5
  ror_ids:
    - https://ror.org/02jbv0t02
  tenant_id: lbnl
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:lbl.gov
    entity_domain: datasets2-dev.lbl.gov
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  enabled: true
  campus_contacts: [""]
