# Logos for a tenant are kept at app/assets/images/tenants and may be a svg, png or jpg file
# with the name logo_<tenant_id>.<ext> .

# Similarly, the about and help pages may be customized by adding files to app/views/tenants/<tenant_id>/ .
# The files are in Markdown format and named such as _about.html.md and _help.html.md

default: &default
  enabled: true
  repository:
    domain: localhost
    endpoint: "http://localhost:39001/sword/collection/stash"
    username: "stash_submitter"
    password: "correct​horse​battery​staple"
  abbreviation: "LH"
  short_name: "Localhost"
  long_name: "Localhost"
  publisher_id: grid.1234567890
  tenant_id: localhost
  authentication:
    strategy: none
  default_license: cc0
  campus_contacts: [""] # for testing
  data_deposit_agreement: false
  partner_display: false

development:
  <<: *default

test:
  <<: *default
