default: &default
  enabled: true
  abbreviation: "Macalester"
  short_name: "Macalester College"
  long_name: "Macalester College"
  publisher_id: grid.259382.7
  ror_ids:
    - https://ror.org/04fceqm38
  tenant_id: macalester
  authentication:
    strategy: shibboleth
    entity_id: https://idp.macalester.edu/openathens
    entity_domain: macalester.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true
  payment_plan: tiered

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

