default: &default
  enabled: true
  abbreviation: "MQ"
  short_name: "Macquarie University"
  long_name: "Macquarie University"
  publisher_id: grid.1004.5
  ror_ids:
    - https://ror.org/01sf06y89
  tenant_id: mq
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:federation.org.au:testfed:mq.edu.au
    entity_domain: mq.edu.au
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here


production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["shawn.ross@mq.edu.au"]
