default: &default
  enabled: true
  abbreviation: "MSU"
  short_name: "Montana State University"
  long_name: "Montana State University"
  publisher_id: grid.41891.35
  ror_ids:
    - https://ror.org/02w0trx84
    - https://ror.org/04ygywa46
    - https://ror.org/0343myz07
  tenant_id: msu
  authentication:
    strategy: shibboleth
    entity_id: https://login.montana.edu/idp/shibboleth
    entity_domain: login.montana.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

