default: &default
  enabled: true
  abbreviation: "MSU2"
  short_name: "Michigan State University"
  long_name: "Michigan State University"
  publisher_id: grid.17088.36
  ror_ids:
    - https://ror.org/05hs6h993
  tenant_id: msu2
  authentication:
    strategy: shibboleth
    # one of these two entity ids since both seem plausible
    # "urn:mace:incommon:msu.edu"
    # "https://sp-dev.idm.msu.edu/incommon/shibboleth"
    entity_id: "urn:mace:incommon:msu.edu"
    entity_domain: msu.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
