default: &default
  enabled: true
  abbreviation: "NCSU"
  short_name: "North Carolina State University"
  long_name: "North Carolina State University"
  publisher_id: grid.40803.3f
  ror_ids:
    - https://ror.org/04tj63d06
  tenant_id: ncsu
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ncsu.edu
    entity_domain: ncsu.edu
  default_license: cc0
  campus_contacts: []
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: ["slivey@ncsu.edu", "hmdavis4@ncsu.edu", "mcdowney@ncsu.edu"]
