default: &default
  enabled: true
  abbreviation: "NCSU"
  short_name: "North Carolina State University"
  long_name: "North Carolina State University"
  publisher_id: grid.40803.3f
  ror_ids:
    - https://ror.org/04tj63d06
  tenant_id: ncsu
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ncsu.edu
    entity_domain: ncsu.edu
  default_license: cc0
  campus_contacts: []
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["slivey@ncsu.edu", "mcdowney@ncsu.edu"]
