default: &default
  enabled: true
  abbreviation: "NIOO-KNAW"
  short_name: "Nederlands Instituut voor Ecologie"
  long_name: "Netherlands Institute of Ecology (NIOO-KNAW)"
  publisher_id: grid.418375.c
  ror_ids:
    - https://ror.org/01g25jp36
  tenant_id: nioo-knaw
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: http://federation.nioo.knaw.nl/adfs/services/trust
    entity_domain: nioo.knaw.nl
  default_license: cc0
  campus_contacts: ["Library@nioo.knaw.nl"]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false

