default: &default
  enabled: true
  abbreviation: "NMSU"
  short_name: "New Mexico State University"
  long_name: "New Mexico State University"
  publisher_id: grid.24805.3b
  ror_ids:
    - https://ror.org/00hpz7z43
    - https://ror.org/007sts724
    - https://ror.org/01kbvt179
    - https://ror.org/035k7dd86
  tenant_id: nmsu

  authentication:
    strategy: shibboleth
    entity_id: https://sts.windows.net/a3ec87a8-9fb8-4158-ba8f-f11bace1ebaa/
    entity_domain: sts.windows.net
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

  campus_contacts: [""]

