default: &default
  enabled: true
  abbreviation: "OU"
  short_name: "University of Oklahoma"
  long_name: "University of Oklahoma"
  publisher_id: grid.266900.b
  ror_ids:
    - https://ror.org/02aqsxs83
  tenant_id: ou
  authentication:
    strategy: shibboleth
    entity_id: https://shib.ou.edu/idp/shibboleth
    entity_domain: shib.ou.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default

