default: &default
  enabled: true
  abbreviation: "rochester"
  short_name: "University of Rochester"
  long_name: "University of Rochester"
  publisher_id: grid.16416.34
  ror_ids:
    - https://ror.org/022kthw22
    - https://ror.org/00trqv719
  tenant_id: rochester

  authentication:
    strategy: shibboleth
    entity_id: https://uidp-prod.its.rochester.edu/idp/shibboleth
    entity_domain: shib2.its.rochester.edu
  default_license: cc0
  campus_contacts: []
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["s.pugachev@rochester.edu"]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
