default: &default
  enabled: true
  abbreviation: "rockefeller"
  short_name: "Rockefeller University"
  long_name: "The Rockefeller University"
  publisher_id: grid.134907.8
  ror_ids:
    - https://ror.org/0420db125
    - https://ror.org/00jjq6q61
  tenant_id: rockefeller

  authentication:
    strategy: shibboleth
    entity_id: https://rushib.rockefeller.edu/idp/shibboleth
    entity_domain: rushib.rockefeller.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

  campus_contacts: [""]
