default: &default
  enabled: true
  abbreviation: "sheffield"
  short_name: "University of Sheffield"
  long_name: "The University of Sheffield"
  publisher_id: grid.11835.3e
  ror_ids:
    - https://ror.org/05krs5044
  tenant_id: sheffield

  authentication:
    strategy: shibboleth
    entity_id: https://idp-qa.shef.ac.uk/shibboleth
    entity_domain: shef.ac.uk
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

  authentication:
    strategy: shibboleth
    entity_id: https://idp.shef.ac.uk/shibboleth
    entity_domain: shef.ac.uk
  campus_contacts: [""]

