default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "Stanford"
  short_name: "Stanford University"
  long_name: "Lane Medical Library, Stanford University"
  publisher_id: grid.168010.e
  ror_ids:
    - https://ror.org/00f54p054
    - https://ror.org/03mtd9a03
    - https://ror.org/019wqcg20
    - https://ror.org/05s570m15
    - https://ror.org/05gzmn429
    - https://ror.org/011pcwc98
  tenant_id: stanford
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:stanford.edu
    entity_domain: stanford.edu
  default_license: cc0
  ## maximum total size (default 100 MB for now)
  max_submission_size: 3.0e+11
  max_total_version_size: 1.0e+10
  max_files: 1000
  campus_contacts: ["jborghi@stanford.edu"]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %>

production:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_password] %>
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
