default: &default
  enabled: true
  abbreviation: "Stanford"
  short_name: "Stanford University"
  long_name: "Stanford University, Lane Medical Library"
  publisher_id: grid.168010.e
  ror_ids:
    - https://ror.org/00f54p054
    - https://ror.org/03mtd9a03
    - https://ror.org/019wqcg20
    - https://ror.org/05s570m15
    - https://ror.org/05gzmn429
    - https://ror.org/011pcwc98
  tenant_id: stanford
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:stanford.edu
    entity_domain: stanford.edu
  default_license: cc0
  campus_contacts: ["jborghi@stanford.edu"]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
