default: &default
  enabled: true
  abbreviation: "UB"
  short_name: "SUNY Buffalo"
  long_name: "University at Buffalo"
  publisher_id: grid.273335.3
  ror_ids:
    - https://ror.org/01y64my43
  tenant_id: suny-buffalo
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:buffalo.edu
    entity_domain: buffalo.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false

