default: &default
  enabled: true
  abbreviation: "Fredonia"
  short_name: "SUNY Fredonia"
  long_name: "State University of New York at Fredonia"
  publisher_id: grid.264268.c
  ror_ids:
    - "https://ror.org/05vrs0r17"
  tenant_id: suny-fredonia
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: ip_address
    ranges: [ "141.238.0.0/16", "141.238.1.23/24" ]
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false

