default: &default
  enabled: true
  abbreviation: "SBU"
  short_name: "SUNY Stony Brook"
  long_name: "Stony Brook University"
  publisher_id: grid.36425.36
  ror_ids:
    - https://ror.org/05qghxh33
  tenant_id: suny-stonybrook

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:stonybrook.edu
    entity_domain: stonybrook.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here


