default: &default
  enabled: true
  abbreviation: "temple"
  short_name: "Temple University"
  long_name: "Temple University"
  publisher_id: grid.264727.2
  ror_ids:
    - https://ror.org/00kx1jb78
    - https://ror.org/04zzmzt85
  tenant_id: temple
  authentication:
    strategy: shibboleth
    entity_id: https://fim.temple.edu/idp/shibboleth
    entity_domain: temple.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
