default: &default
  enabled: true
  abbreviation: "test"
  short_name: "Test tenant"
  long_name: "Test tenant"
  publisher_id: grid.471410.7
  ror_ids:
    - https://ror.org/02r109517
    - https://ror.org/05v5hg569
  tenant_id: test-tenant

  authentication:
    strategy: shibboleth
    entity_id: https://login.weill.cornell.edu/idp
    entity_domain: login.weill.cornell.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false
  partner_display: false

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
