default: &default
  enabled: true
  abbreviation: "UArk"
  short_name: "University of Arkansas"
  long_name: "University of Arkansas at Fayetteville"
  publisher_id: grid.411017.2
  ror_ids:
    - https://ror.org/05jbt9m15
  tenant_id: uark
  authentication:
    strategy: shibboleth
    entity_id: https://idp.uark.edu/idp/shibboleth
    entity_domain: uark.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default

