default: &default
  enabled: true
  abbreviation: "ubc"
  short_name: "University of British Columbia"
  long_name: "The University of British Columbia"
  publisher_id: grid.17091.3e
  ror_ids:
    - https://ror.org/03rmrcq20
  tenant_id: ubc

  authentication:
    strategy: shibboleth
    entity_id: https://authentication.ubc.ca
    entity_domain: authentication.ubc.ca
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default

