default: &default
  enabled: true
  abbreviation: "UCB"
  short_name: "UC Berkeley"
  long_name: "University of California, Berkeley"
  publisher_id: grid.47840.3f
  ror_ids:
    - https://ror.org/01an7q238
    - https://ror.org/03djjyk45
    - https://ror.org/01ewh7m12
    - https://ror.org/03rafms67
    - https://ror.org/05kbg7k66
    - https://ror.org/02mmp8p21
  tenant_id: ucb
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:berkeley.edu
    entity_domain: .berkeley.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: ezid
    shoulder: "doi:10.6078/D1"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  campus_contacts: ["asackmann@berkeley.edu"]
