default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "UCB"
  short_name: "UC Berkeley"
  long_name: "University of California, Berkeley"
  publisher_id: grid.47840.3f
  ror_ids:
    - https://ror.org/01an7q238
    - https://ror.org/03djjyk45
    - https://ror.org/01ewh7m12
    - https://ror.org/03rafms67
    - https://ror.org/05kbg7k66
    - https://ror.org/02mmp8p21
  tenant_id: ucb
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:berkeley.edu
    entity_domain: .berkeley.edu
  default_license: cc0
  ## maximum total size (default 100 GB for now)
  max_submission_size: 3.0e+11
  max_total_version_size: 1.0e+10
  max_files: 1000
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %> 

production:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucb_dash"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_ucb_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_ucb_password] %> 
  identifier_service:
    provider: ezid
    shoulder: "doi:10.6078/D1"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  campus_contacts: ["asackmann@berkeley.edu"]
