default: &default
  enabled: true
  abbreviation: "Irvine"
  short_name: "UC Irvine"
  long_name: "University of California, Irvine"
  publisher_id: grid.266093.8
  ror_ids:
    - https://ror.org/04gyf1771
    - https://ror.org/03fgher32
    - https://ror.org/00cm8nm15
    - https://ror.org/03bfp2076
  tenant_id: uci

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:uci.edu
    entity_domain: .lib.uci.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["lsmart@uci.edu", "kaned@uci.edu", "wdahdul@uci.edu"]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
