default: &default
  enabled: true
  abbreviation: "UCLA"
  short_name: "UC Los Angeles"
  long_name: "University of California, Los Angeles"
  publisher_id: grid.19006.3e
  ror_ids:
    - https://ror.org/046rm7j60
    - https://ror.org/05h4zj272
    - https://ror.org/04p5baq95
    - https://ror.org/03b66rp04
    - https://ror.org/04k3jt835
    - https://ror.org/01d88se56
    - https://ror.org/04vq5kb54
    - https://ror.org/00mjfew53
  tenant_id: ucla

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucla.edu
    entity_domain: .ucla.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["tdennis@library.ucla.edu"]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
