default: &default
  enabled: true
  abbreviation: "Merced"
  short_name: "UC Merced"
  long_name: "University of California, Merced"
  publisher_id: grid.266096.d
  ror_ids:
    - https://ror.org/00d9ah105
  tenant_id: ucm

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucmerced.edu
    entity_domain: .ucmerced.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  enabled: false
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

  campus_contacts: ["elin@ucmerced.edu","ddevnich@ucmerced.edu"]
