default: &default
  enabled: true
  abbreviation: "UC"
  short_name: "UC Office of the President"
  long_name: "University of California, Office of the President"
  publisher_id: grid.30389.31
  # this is "UC System" since there isn't something for UC Office of the President
  ror_ids:
    - https://ror.org/00pjdza24
  tenant_id: ucop

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucop.edu
    entity_domain: .ucop.edu
  default_license: cc0
  campus_contacts: ["scott.fisher@ucop.edu"] # for testing
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
