default: &default
  enabled: true
  abbreviation: "UCSB"
  short_name: "UC Santa Barbara"
  long_name: "University of California, Santa Barbara"
  publisher_id: grid.133342.4
  ror_ids:
    - https://ror.org/02t274463
  tenant_id: ucsb
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucsb.edu
    entity_domain: .ucsb.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: true
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default
  enabled: false

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: ezid
    shoulder: "doi:10.25349/D9"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  campus_contacts: ["rds@library.ucsb.edu"]

test:
  <<: *default
  #Add any items that need to override the defaults here
