default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "UCSC"
  short_name: "UC Santa Cruz"
  long_name: "University of California, Santa Cruz"
  publisher_id: grid.205975.c
  ror_ids:
    - https://ror.org/03s65by71
  tenant_id: ucsc
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucsc.edu
    entity_domain: .library.ucsc.edu
  default_license: cc0
  ## maximum total size (default 100 MB for now)
  max_submission_size: 3.0e+11
  max_total_version_size: 1.0e+10
  max_files: 1000
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %>

migration:
  <<: *default
  enabled: false

demo:
  <<: *default
  enabled: false

production:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/ucsc_dash"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_ucsc_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_ucsc_password] %> 
  identifier_service:
    provider: ezid
    shoulder: "doi:10.7291/D1"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null

test:
  <<: *default
  #Add any items that need to override the defaults here
