default: &default
  enabled: true
  abbreviation: "UCSD"
  short_name: "UC San Diego"
  long_name: "University of California, San Diego"
  publisher_id: grid.266100.3
  ror_ids:
    - https://ror.org/0168r3w48
    - https://ror.org/01kbfgm16
    - https://ror.org/04mg3nk07
    - https://ror.org/05ffhwq07
    - https://ror.org/04v7hvq31
    - https://ror.org/01vf2g217
  tenant_id: ucsd

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucsd.edu
    entity_domain: .ucsd.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: true
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: true

  campus_contacts: ["tmarconi@ucsd.edu"]

test:
  <<: *default
  #Add any items that need to override the defaults here
