default: &default
  enabled: true
  abbreviation: "UIUC"
  short_name: "University of Illinois Urbana-Champaign"
  long_name: "University of Illinois, Urbana-Champaign"
  publisher_id: grid.35403.31
  ror_ids:
    - https://ror.org/047426m28
  tenant_id: uiuc

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:uiuc.edu
    entity_domain: uiuc.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here
