default: &default
  enabled: true
  abbreviation: "UMN"
  short_name: "University of Minnesota"
  long_name: "University of Minnesota"
  publisher_id: grid.17635.36
  ror_ids:
    - https://ror.org/017zqws13
    - https://ror.org/01hy4qx27
    - https://ror.org/03grvy078
    - https://ror.org/02rh4fw73
    - https://ror.org/0241gfe92
    - https://ror.org/04w6xt508
    - https://ror.org/05vzqzh92
    - https://ror.org/03e1ayz78
    - https://ror.org/04jnprq39
    - https://ror.org/05jc5ee02
  tenant_id: umn

  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:umn.edu
    entity_domain: umn.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here

  campus_contacts: ["ljohnsto@umn.edu", "datarepo@umn.edu"]

test:
  <<: *default
  #Add any items that need to override the defaults here
