default: &default
  enabled: true
  abbreviation: "UNM"
  short_name: "University of New Mexico"
  long_name: "University of New Mexico"
  publisher_id: grid.266832.b
  ror_ids:
    - https://ror.org/05fs6jp91
    - https://ror.org/01aq2mh35
    - https://ror.org/02jp62t23
    - https://ror.org/04skph061
  tenant_id: unm
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: https://unmpidp.unm.edu/idp/shibboleth
    entity_domain: unmpidp.unm.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here
