default: &default
  enabled: true
  abbreviation: "UNR"
  short_name: "University of Nevada"
  long_name: "University of Nevada, Reno"
  publisher_id: grid.266818.3
  ror_ids:
    - https://ror.org/01keh0577
  tenant_id: unr

  authentication:
    strategy: shibboleth
    entity_id: https://idp2.unr.edu/idp/shibboleth
    entity_domain: unr.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
