default: &default
  enabled: true
  abbreviation: "UPenn"
  short_name: "University of Pennsylvania"
  long_name: "University of Pennsylvania"
  publisher_id: grid.25879.31
  ror_ids:
    - https://ror.org/00b30xv10
    - https://ror.org/047939x15
    - https://ror.org/02917wp91
    - https://ror.org/04h81rw26
  tenant_id: upenn

  authentication:
    strategy: shibboleth
    entity_id: https://idp.pennkey.upenn.edu/idp/shibboleth
    entity_domain: upenn.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
