default: &default
  enabled: true
  abbreviation: "WISC"
  short_name: "University of Wisconsin–Madison"
  long_name: "University of Wisconsin–Madison"
  publisher_id: grid.14003.36
  ror_ids:
    - https://ror.org/01y2jtd41
  tenant_id: wisc

  authentication:
    strategy: shibboleth
    entity_id: https://login.wisc.edu/idp/shibboleth
    entity_domain: login.wisc.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
