default: &default
  enabled: true
  abbreviation: "YALE"
  short_name: "Yale"
  long_name: "Yale University"
  publisher_id: grid.47100.32
  ror_ids:
    - https://ror.org/03v76x132
    - https://ror.org/03pnmqc26
  tenant_id: yale

  authentication:
    strategy: shibboleth
    entity_id: https://auth.yale.edu/idp/shibboleth
    entity_domain: auth.yale.edu
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: [""]

test:
  <<: *default
  #Add any items that need to override the defaults here

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *default
