language: ruby
services:
  - mysql
before_install:
  - gem update --system 2.6.8
  - git clone https://github.com/CDLUC3/stash_engine.git ../stash_engine
  - git clone https://github.com/CDLUC3/stash_discovery.git ../stash_discovery
before_script:
  # - ./remote_upload_script.sh
  - mysql -e 'create database stash_datacite_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load
script:
  - cd $TRAVIS_BUILD_DIR/
  - cd spec/dummy/ && RAILS_ENV=test bundle exec rails server -d && cd ../../
  - bundle exec rspec spec/features/metadata_entry_page_with_incomplete_data_notification_spec.rb
  - bundle exec rspec spec/features/metadata_entry_page_with_geo_spec.rb
  - bundle exec rspec spec/features/uploads_page_spec.rb
  # - bundle exec rspec spec/features/update_and_resubmit_dataset_spec.rb
  # - bundle exec rspec spec/features/test_end_to_end_spec.rb
branches:
  only:
    - development
notifications:
  email:
    on_success: change
    on_failure: always
#test commit for travis.
addons:
  sauce_connect: true
