# ------------------------------------------------------------
# RSpec

require 'rspec/core'
require 'rspec/core/rake_task'

namespace :spec do
  desc 'Run unit and database tests as single suite (for coverage)'
  task :unified do
    puts "TODO: unit & db specs for #{File.basename(__dir__)}"
  end

  desc 'Run Selenium feature tests'
  task :feature do
    puts "TODO: feature specs for #{File.basename(__dir__)}"
  end
end

# ------------------------------------------------------------
# Coverage

desc 'Run all unit tests with coverage'
task :coverage do
  ENV['COVERAGE'] = 'true'
  Rake::Task['spec:unified'].execute
end

# ------------------------------------------------------------
# RuboCop

require 'rubocop/rake_task'
RuboCop::RakeTask.new

# ------------------------------------------------------------
# Defaults

desc 'Run unit tests, check test coverage, check code style, run feature tests'
task default: %i[coverage rubocop spec:feature]

# require 'rubygems'
# begin
#   require 'bundler/setup'
# rescue LoadError
#   puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
# end
# require 'rdoc/task'
# require 'rake'
# require 'rspec/core/rake_task'
#
# RDoc::Task.new(:rdoc) do |rdoc|
#   rdoc.rdoc_dir = 'rdoc'
#   rdoc.title    = 'StashDatacite'
#   rdoc.options << '--line-numbers'
#   rdoc.rdoc_files.include('README.rdoc')
#   rdoc.rdoc_files.include('lib/**/*.rb')
# end
#
# APP_RAKEFILE = File.expand_path('../spec/dummy/Rakefile', __FILE__)
# load 'rails/tasks/engine.rake'
# load 'rails/tasks/statistics.rake'
# Bundler::GemHelper.install_tasks
#
# RSpec::Core::RakeTask.new(:spec) do |t|
#   t.pattern = Dir.glob('spec/**/*_spec.rb')
#   t.rspec_opts = '--format documentation'
# end
# task default: :spec
