source 'https://rubygems.org'

gem 'activesupport', '~> 4.2'
gem 'byebug', '>= 11.0.1'
gem 'httpclient', '>= 2.8.3'
gem 'nokogiri'
# gem 'oai', '~> 1.1.0'  # this seems to work fine without it and there aren't compatible versions that work with geoblacklight
gem 'rake', '>= 12.3.2'
gem 'rspec', '>= 3.8.0'
gem 'rubocop', '~> 0.85.1'
gem 'webmock'
