extends: airbnb
parserOptions:
  ecmaVersion: 2020
rules:
  "react/forbid-prop-types": [2, { "forbid": [], "checkContextTypes": false, "checkChildContextTypes": false}]
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/jsx-one-expression-per-line": [0, { "allow": "single-child" }] # does bad things to our code like see https://github.com/yannickcr/eslint-plugin-react/issues/1855
  camelcase: off # because of some variable names being the same as rails and transferring across, maybe can go back and fix
  "max-len": [2, {"code": 150, "tabWidth": 2, "ignoreUrls": true}]
env:
  "browser": true # includes browser variables like document, window, etc


