source 'https://rubygems.org'

gemspec

gem 'standalone_migrations', git: 'https://github.com/thuss/standalone-migrations.git', ref: 'de391a69e4ed'
gem 'byebug'

path '..' do
  gem 'stash-sword'
  gem 'stash-wrapper'
  gem 'stash_datacite'
  gem 'stash_discovery'
  gem 'stash_engine'
end
