source 'https://rubygems.org'

gemspec

group :development, :local_dev, :test do
  gem 'byebug'
  gem 'colorize'
  gem 'diffy'
  gem 'equivalent-xml'
  gem 'factory_bot_rails', require: false
  gem 'nokogiri'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'yard'
end
