language: ruby
services:
  - mysql
before_script:
  - mysql -e 'create database stash_engine_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
  - bundle exec rubocop -R
branches:
  only:
    - development
notifications:
  email:
    on_success: change
    on_failure: always

