source 'https://rubygems.org'

gemspec

gem 'mysql2', '~> 0.5.3'
gem 'stash-sword', path: '../stash-sword'
gem 'zaru', '~> 0.3' # Gem for sanitizing file names

group :development,  :local_dev, :test do
  gem 'byebug'
  gem 'colorize'
  gem 'database_cleaner'
  gem 'diffy'
  gem 'equivalent-xml'
  gem 'factory_bot_rails', require: false
  gem 'nokogiri'
  gem 'rspec', '~> 3.5'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', '0.85.1'
  gem 'scss_lint'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'webdrivers' # used to be chromedriver-helper, now deprecated
  gem 'webmock'
end
