inherit_from: ../../.rubocop.yml

# NOTE:
#   We can't depend on the top-level (Method|Module|Block)Length
#   spec-directory disables because the engine-level .rubocop.yml
#   (that is, ../.rubocop-yml) overrides those declarations

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# These 'set' methods aren't conventional accessors, but Rubocop doesn't know that
Naming/AccessorMethodName:
  Exclude:
    - 'util/resource_builder.rb'
