source 'https://rubygems.org'

gemspec

# gem 'sword2ruby', git: 'https://github.com/dmolesUC3/sword2ruby.git'
# gem 'multipart-post', git: 'https://github.com/dmolesUC3/multipart-post'

group :development, :local_dev, :test do
  gem 'byebug'
  gem 'colorize'
  gem 'database_cleaner'
  gem 'diffy'
  gem 'equivalent-xml'
  gem 'factory_bot_rails', require: false
  gem 'nokogiri'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'webmock'
  gem 'yard'
end
