source 'https://rubygems.org'

path '..' do
  gem 'stash-sword'
  gem 'stash-wrapper'
  gem 'stash_engine'
end

gem 'database_cleaner', '~> 1.5'
gem 'diffy', '~> 3.1'
gem 'equivalent-xml', '~> 0.6.0'
gem 'mysql2', '~> 0.3'
gem 'nokogiri', '1.6.8.1'
gem 'rspec', '~> 3.5'
gem 'rspec-rails', '~> 3.5'
gem 'rubocop', '~> 0.42'
gem 'simplecov', '~> 0.12'
gem 'simplecov-console', '~> 0.3.0'
gem 'webmock', '~> 3.0'
