test:
  page_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  submission_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  feedback_email_from: stash-noreply@example.edu
  repository: Stash::MockRepository
  submission_bc_emails: ["alan.smithee@example.edu"]
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  old_dryad_access_token: "this-is-not-a-real-token"
  old_dryad_url: http://v1.datadryad.org
  payments:
    service: stripe
    key: travis_test_key
    data_processing_charge: 12000 # charge in cents
    large_file_size: 5.0e+10 # 50 GB
    additional_storage_chunk_size: 1.0e+10 # 10 GB
    additional_storage_chunk_cost: 5000 # in cents
  merritt_express_base_url: http://dummy_domain.example.com
  fee_waiver_countries:
    - 'Afghanistan'
    - 'Guinea-Bissau'
    - 'Sierra Leone'
    - 'Benin'
    - 'Haiti'
    - 'Somalia'
    - 'Burkina Faso'
    - 'North Korea'
    - 'South Sudan'
    - 'Burundi Liberia'
    - 'Syria'
    - 'Central African Republic'
    - 'Madagascar'
    - 'Tajikistan'
    - 'Chad'
    - 'Malawi'
    - 'Tanzania'
    - 'Comoros'
    - 'Mali'
    - 'Togo'
    - 'Republic of the Congo'
    - 'Democratic Republic of the Congo'
    - 'Mozambique'
    - 'Uganda'
    - 'Eritrea'
    - 'Nepal'
    - 'Yemen'
    - 'Ethiopia'
    - 'Niger'
    - 'Zimbabwe'
    - 'Gambia'
    - 'Rwanda'
    - 'Guinea'
    - 'Senegal'
    - 'Angola'
    - 'Indonesia'
    - 'Papua New Guinea'
    - 'Bangladesh'
    - 'Kenya'
    - 'Philippines'
    - 'Bhutan'
    - 'Kiribati'
    - 'Sao Tome and Principe'
    - 'Bolivia'
    - 'Kosovo'
    - 'Solomon Islands'
    - 'Cabo Verde'
    - 'Kyrgyzstan'
    - 'Sri Lanka'
    - 'Cambodia'
    - 'Laos'
    - 'Sudan'
    - 'Cameroon'
    - 'Lesotho'
    - 'Swaziland'
    - 'Congo'
    - 'Mauritania'
    - 'East Timor'
    - 'Ivory Coast'
    - 'Micronesia'
    - 'Tunisia'
    - 'Djibouti'
    - 'Moldova'
    - 'Ukraine'
    - 'Egypt'
    - 'Mongolia'
    - 'Uzbekistan'
    - 'El Salvador'
    - 'Morocco'
    - 'Vanuatu'
    - 'Georgia'
    - 'Myanmar'
    - 'Vietnam'
    - 'Ghana'
    - 'Nicaragua'
    - 'State of Palestine'
    - 'Honduras'
    - 'Nigeria'
    - 'Zambia'
    - 'India'
    - 'Pakistan'
  link_out:
    # LinkOut FTP information for Europe PubMed Central
    labslink:
      ftp_host: labslink.example.org
      ftp_dir: testing
      ftp_username: username
      ftp_password: password
      ftp_provider_id: 1234
    # LinkOut FTP information for NCBI
    pubmed:
      ftp_host: pubmed.example.org
      ftp_dir: testing
      ftp_username: username
      ftp_password: password
      ftp_provider_id: 5678
