test:
  page_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  submission_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  feedback_email_from: stash-noreply@example.edu
  repository: Stash::MockRepository
  submission_bc_emails: ["alan.smithee@example.edu"]
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  old_dryad_access_token: "this-is-not-a-real-token"
  old_dryad_url: http://api.datadryad.org
  payments:
    service: stripe
    key: travis_test_key
    data_processing_charge: 12000 # charge in cents
