inherit_from: ../.rubocop.yml

# Don't check generated files
AllCops:
  Exclude:
    - 'db/schema.rb'
  TargetRubyVersion: 2.2

# Suppress complaints about binaries not being named .rb
Naming/FileName:
  Exclude:
   - 'bin/*'
