class AddIndexesWhereNeeded < ActiveRecord::Migration[4.2]
  # rubocop:disable Metrics/MethodLength
  def change
    add_index(:dcs_affiliations, :short_name, length: { short_name: 50 })
    add_index(:dcs_affiliations, :long_name, length: { long_name: 50 })
    add_index(:dcs_affiliations_contributors, :affiliation_id)
    add_index(:dcs_affiliations_contributors, :contributor_id)
    add_index(:dcs_affiliations_creators, :affiliation_id)
    add_index(:dcs_affiliations_creators, :creator_id)
    add_index(:dcs_alternate_identifiers, :resource_id)
    add_index(:dcs_contributors, :name_identifier_id)
    add_index(:dcs_contributors, :resource_id)
    add_index(:dcs_creators, :name_identifier_id)
    add_index(:dcs_creators, :resource_id)
    add_index(:dcs_dates, :resource_id)
    add_index(:dcs_descriptions, :resource_id)
    add_index(:dcs_embargoes, :resource_id)
    add_index(:dcs_formats, :resource_id)
    add_index(:dcs_geo_location_boxes, :resource_id)
    add_index(:dcs_geo_location_places, :resource_id)
    add_index(:dcs_geo_location_points, :resource_id)
    add_index(:dcs_languages, :resource_id)
    add_index(:dcs_name_identifiers, :name_identifier, length: { name_identifier: 50 })
    add_index(:dcs_publication_years, :resource_id)
    add_index(:dcs_publishers, :resource_id)
    add_index(:dcs_related_identifiers, :related_identifier, length: { related_identifier: 50 })
    add_index(:dcs_related_identifiers, :resource_id)
    add_index(:dcs_resource_types, :resource_id)
    add_index(:dcs_rights, :resource_id)
    add_index(:dcs_sizes, :resource_id)
    add_index(:dcs_subjects, :subject, length: { subject: 50 })
    add_index(:dcs_subjects_stash_engine_resources, :resource_id)
    add_index(:dcs_subjects_stash_engine_resources, :subject_id)
    add_index(:dcs_titles, :resource_id)
    add_index(:dcs_versions, :resource_id)
  end
  # rubocop:enable Metrics/MethodLength
end
