test:
  page_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  submission_error_email: [stash-dev@example.edu, stash-ops@example.edu]
  feedback_email_from: stash-noreply@example.edu
  repository: Stash::MockRepository
