Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shibboleth,
           callback_path: '/stash/auth/shibboleth/callback',
           request_type: :header,
           host: APP_CONFIG.shib_sp_host,
           uid_field: 'eppn',
           path_prefix: '/stash/auth',
           info_fields: {
             email: 'mail',
             identity_provider: 'shib_identity_provider'
           }

  provider :orcid, APP_CONFIG.orcid.key, APP_CONFIG.orcid.secret,
           member: APP_CONFIG.orcid.member,
           sandbox: APP_CONFIG.orcid.sandbox,
           callback_path: '/stash/auth/orcid/callback',
           path_prefix: '/stash/auth',
           authorize_params: {
             scope: '/read-limited'
           },
           client_options: {
             site: APP_CONFIG.orcid_site,
             authorize_url: APP_CONFIG.orcid.authorize_url,
             token_url: APP_CONFIG.orcid.token_url
           }

  provider :google_oauth2, APP_CONFIG[:google][:gmail_client_id], APP_CONFIG[:google][:gmail_client_secret],
           skip_jwt: true,
           callback_path: '/stash/auth/google_oauth2/callback'
  
  # patch to help prevent CSRF for CVE-2015-9284
  OmniAuth.config.allowed_request_methods = [:post]

  # this is to deal with http URLs being generated by omniauth when we want https but we have a reverse proxy that disguises we're using https
  OmniAuth.config.full_host = ->(env) do
    # "omniauth.strategy"=>#<OmniAuth::Strategies::ORCID> might be helpful if we need to know if strategy is ORCID
    u = URI.parse("http://#{env['HTTP_X_FORWARDED_HOST'] || env['HTTP_HOST']}")
    u.scheme = 'https' if env['omniauth.strategy'].to_s.include?('ORCID') && !u.host[/(localhost)|(.+dash\.datadryad\.org)|(docker)/]
    "#{u.scheme}://#{u.host}#{(u.port == 80 ? '' : ":#{u.port}")}" # only add port if it's not 80
  end

  ## Omniauth on_failure behavior to work for all ENV including localhost
  OmniAuth.config.on_failure = ->(env) do
    Rack::Response.new(['302 Moved'], 302, 'Location' => env['omniauth.origin'] || '/').finish
  end
end

