# frozen_string_literal: true

source 'https://rubygems.org'

# Declare your gem's dependencies in stash_api.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

gem 'doorkeeper'
gem 'mysql2', '< 0.5'

# To use a debugger
# gem 'byebug', group: [:development, :test]

path '..' do
  gem 'stash_datacite'
  gem 'stash_engine'
end

group :development, :test do
  gem 'rspec-rails'
end
