inherit_from: ../../.rubocop.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
