source 'https://rubygems.org'

# Declare your gem's dependencies in stash_discovery.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

group :development,  :local_dev, :test do
  gem 'nokogiri'
  gem 'rspec', '~> 3.5'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', '0.57.2'
  gem 'scss_lint'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'sqlite3'
end
