import React from 'react';
import {ExitIcon} from '../../ExitButton';
import FrictionlessReport from './FrictionlessReport';

const ModalValidationReport = React.forwardRef(({file, clickedClose}, ref) => {
  const jsReport = file?.frictionless_report?.report ? JSON.parse(file.frictionless_report.report) : {};
  return (
    <dialog
      className="modalDialog extra-wide"
      aria-modal="true"
      ref={ref}
    >
      <div className="c-uploadmodal__header">
        <h1 className="c-datasets-heading__heading o-heading__level1">
          Formatting report: {file?.sanitized_name}
        </h1>
        <button
          className="button-close-modal"
          aria-label="close"
          type="button"
          onClick={clickedClose}
        />
      </div>
      <p>
        This report has been generated by our tabular data checker.
        Please{' '}
        <a href="/data_check_guide" target="_blank">review the alerts<ExitIcon /></a>
        {' '}and, if desired, correct and re-upload the file:
      </p>
      <ol>
        <li>Review the local copy of your file and make any desired changes.</li>
        <li>
          To replace the file, close this dialog, and click the button in the
          {' '}<em>Remove</em> column to delete the current upload.
        </li>
        <li>
          Re-upload the corrected file using the &quot;Choose files&quot; or &quot;Enter URLs&quot; button.
        </li>
      </ol>
      {file && <FrictionlessReport tdc_report={jsReport} />}
      <p>
        You can choose to proceed to the final page of the submission form without editing your file.
        A curator may contact you with options to improve the organization, readability, and/or accessibility of your dataset.
      </p>
      <p style={{textAlign: 'right'}}>
        <button type="button" className="o-button__plain-text2" onClick={clickedClose}>Close</button>
      </p>
    </dialog>
  );
});

export default ModalValidationReport;
