import React from 'react';

import '@cdl-dryad/frictionless-components/lib/styles';
import {render} from '@cdl-dryad/frictionless-components/lib/render';
import {Report} from '@cdl-dryad/frictionless-components/lib/components/Report';

import classes from './ModalValidationReport.module.css';

const ModalValidationReport = React.forwardRef(({file, clickedClose, report}, ref) => {
  if (!file) return null;
  const element = document.getElementById('validation_report');
  render(Report, JSON.parse(report), element);
  return (
    <dialog
      className="c-uploadmodal"
      style={{
        position: 'fixed',
        width: '60%',
        maxWidth: '950px',
        minWidth: '220px',
      }}
      ref={ref}
    >
      <div className="c-uploadmodal__header">
        <h2 className="c-datasets-heading__heading o-heading__level1">
          Formatting Report:
          {file.sanitized_name}
        </h2>
        <button
          className={classes.CloseButton}
          aria-label="close"
          type="button"
          onClick={clickedClose}
        />
      </div>
      <div>
        This report has been generated by our tabular data checker. Please resolve the following formatting
        issues and re-upload the file:
      </div>
      <ol>
        <li>
          Manually correct the issues shown here in your local copy of the file.
        </li>
        <li>
          Close this dialog and click <em>Remove</em> in the Action column to delete the file.
        </li>
        <li>
          Re-upload the corrected file using the
          <em>Choose Files</em> or <em>Enter URLs</em> button.
        </li>
      </ol>
      <div id="validation_report" />
      <button type="button" onClick={clickedClose}>Close</button>
    </dialog>
  );
});

export default ModalValidationReport;
