test:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/geoblacklight" %>

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/geoblacklight" %>

dev:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://v3-dev-solr.datadryad.org:8983/solr/geoblacklight" %>

stage:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://v3-stage-solr.datadryad.org:8983/solr/geoblacklight" %>

production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://v3-solr.datadryad.org:8983/solr/geoblacklight" %>
