development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/dryad" %>

test:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/dryad" %>

dev:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://18.236.111.137:8983/solr/dryad" %>

stage:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://34.215.143.38:8983/solr/dryad" %>

production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://35.91.212.8:8983/solr/dryad" %>
