# When in the 'test' environment, only use the content from dryad-config-example, not the content
# in the main part of this file.

# blacklight yaml parsing now no longer allows inheriting settings from an alias
test:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/geoblacklight" %>

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-dev.cdlib.org:8983/solr/geoblacklight" %>

v3_development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-dev.cdlib.org:8983/solr/geoblacklight" %>

aws_db:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-dev.cdlib.org:8983/solr/geoblacklight" %>

local:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-dev.cdlib.org:8983/solr/geoblacklight" %>

local_dev:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-dev.cdlib.org:8983/solr/geoblacklight" %>

stage:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-stg.cdlib.org:8983/solr/geoblacklight" %>

v3_stage:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-stg.cdlib.org:8983/solr/geoblacklight" %>

# migration solr not used, but we probably need the section here
migration:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolr-stg.cdlib.org:8983/solr/geoblacklight" %>

demo:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryaddemo-stg.cdlib.org:8983/solr/geoblacklight" %>

production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-prd.cdlib.org:8983/solr/geoblacklight" %>

v3_production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://uc3-dryadsolrx2-prd.cdlib.org:8983/solr/geoblacklight" %>
