default: &default
  pool: 40
  timeout: 10000
  adapter: mysql2
  database: dryad
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database_host] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database_username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database_password] %>
  port: <%= Rails.application.credentials[Rails.env.to_sym][:database_port] %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true

development: &DEVELOPMENT
  <<: *default

v3_development:
  <<: *default

aws_db:
  <<: *default
  host: aws-dev-db.co33oyzjqasf.us-east-1.rds.amazonaws.com
  username: <%= Rails.application.credentials[:development][:database_username] %>
  password: <%= Rails.application.credentials[:development][:database_password] %>

local:
  <<: *default
  host: 127.0.0.1
  username: travis
  password: ""

local_dev:
  <<: *default

test:
  adapter: mysql2
  host: localhost
  database: dashv2_test
  username: travis
  password: ""
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

stage:
  <<: *default

v3_stage:
  <<: *default

production:
  <<: *default

v3_production:
  <<: *default
