source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'byebug'
end
gem 'standalone_migrations', git: 'https://github.com/thuss/standalone-migrations.git', ref: 'de391a69e4ed'

gem 'mysql2', '< 0.5x', '>= 0.3.13'

path '..' do
  gem 'stash-sword'
  gem 'stash-wrapper'
  gem 'stash_datacite'
  gem 'stash_discovery'
  gem 'stash_engine'
end
