# ------------------------------------------------------------
# RSpec

require 'rspec/core'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

namespace :spec do
  desc 'Run all unit tests'
  RSpec::Core::RakeTask.new(:unit) do |task|
    task.rspec_opts = %w[--color --format documentation --order default]
    task.pattern = 'unit/**/*_spec.rb'
  end

end

desc 'Run all tests'
task spec: %w[spec:unit]

# ------------------------------------------------------------
# RuboCop

require 'rubocop/rake_task'
RuboCop::RakeTask.new

# ------------------------------------------------------------
# Defaults

desc 'Run unit tests, check code style'
task default: %i[spec rubocop]
