defaults: &DEFAULTS
  metadata_engine: StashDatacite
  shared_resource_model: StashEngine::Resource
  repository: Stash::Merritt::Repository
  stash_mount: /stash
  max_review_days: 180
  ezid:
    host: ezid.cdlib.org
    port: 443
  google_maps_api_key: <add_key_here>
  contact_us_uri: http://www.cdlib.org/services/uc3/contact.html
  orcid:
    site: https://sandbox.orcid.org/
    authorize_url: https://sandbox.orcid.org/oauth/authorize
    token_url: https://api.sandbox.orcid.org/oauth/token
    key:  <fill-me-in>
    secret: <fill-me-in>
    member: true
    sandbox: true
    api: https://api.sandbox.orcid.org
  submission_bc_emails: [""]
  contact_email: ["changeme@example.org"]


development: &DEVELOPMENT
  <<: *DEFAULTS
  shib_sp_host: <fill-me-in>
  page_error_email: ~
  submission_error_email: [emailme@example.org]
  feedback_email_from: no-reply@example.org
  collection_uri: http://uc3-mrtsword-dev.cdlib.org:39001/mrtsword/
  google_analytics_id: <fill-me-in>

local:
  <<: *DEVELOPMENT

test:
  <<: *DEFAULTS
  repository: Stash::MockRepository
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  default_tenant: localhost
