test:
  metadata_engine: StashDatacite
  shared_resource_model: StashEngine::Resource
  # dashv2/spec/mocks/mock_repository.rb
  repository: Stash::MockRepository
  stash_mount: /stash
  max_review_days: 180
  submission_bc_emails: [""]
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
