test:
  metadata_engine: StashDatacite
  shared_resource_model: StashEngine::Resource
  # dashv2/spec/mocks/mock_repository.rb
  repository: Stash::MockRepository
  stash_mount: /stash
  max_review_days: 180
