name: RSpec Internal Tests

on: [pull_request]

jobs:
  rspec-internal:
    name: RSpec Internal Tests
    runs-on: ubuntu-18.04

    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    - name: 'Checkout the repo'
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Set Ruby and Bundler Versions'
      run: |
        echo "RUBY_VERSION=2.6.6" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby'
      uses: ruby/setup-ruby@v1.68.0
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - name: 'Retrieve Cached Gems'
      uses: actions/cache@v2.1.5
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: 'Bundle Install'
      run: |
        gem install bundler -v ${{ env.BUNDLER_VERSION }}
        bundle config path vendor/bundle
        bundle config set without 'pgsql rollbar aws'
        bundle install --jobs 4 --retry 3

    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Setup Test DB'
      run: |
        mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dashv2_test' 
        mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost'
        mysql -u root -e 'GRANT ALL ON dashv2_test.* TO travis@localhost'  
        bin/rails db:migrate RAILS_ENV=test
        bin/rails db:setup RAILS_ENV=test

    - name: 'RSpec Controller Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/controllers

    - name: 'RSpec Request Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/requests

    - name: 'RSpec Job Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/jobs

    - name: 'RSpec Model Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/models

    - name: 'RSpec Service Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/services

    - name: 'RSpec Library Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/lib

    - name: 'RSpec Task Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/tasks

    - name: 'RSpec Stash-Notifier Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip stash/stash-notifier/spec/
