name: RSpec Response Tests

on:
  pull_request:
    types: [opened, edited, reopened, converted_to_draft, ready_for_review]

jobs:
  rspec-response:
    name: RSpec Request Tests
    runs-on: ubuntu-18.04

    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    - name: 'Checkout the repo'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: 'Set Ruby and Bundler Versions'
      run: |
        echo "RUBY_VERSION=2.6.6" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby and gems'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: 'setup node for node-sass'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Setup Test DB'
      run: |
        mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dashv2_test' 
        mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost'
        mysql -u root -e 'GRANT ALL ON dashv2_test.* TO travis@localhost'  
        bin/rails db:migrate:reset RAILS_ENV=test

    - name: 'Set up Python 3.x'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 'Display Python version'
      run: python -c "import sys; print(sys.version)"

    - name: 'Install frictionless python package'
      run: pip install frictionless==4.38.0

    - name: 'Install frictionless python package for excel'
      run: pip install frictionless[excel]==4.38.0

    - name: 'Install frictionless python package for json'
      run: pip install frictionless[json]==4.38.0

    # I found this https://tech.hey.jp/entry/2021/05/21/134001
    # and this https://github.community/t/cache-rails-assets-generated-by-webpacker/189057/4
    - name: asset cache
      uses: actions/cache@v3
      with:
        path: |
          public/assets
          tmp/cache/assets/sprockets
        key: asset-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          asset-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          asset-cache-${{ runner.os }}-${{ github.ref }}-
          asset-cache-${{ runner.os }}-

        - name: 'assets precompile'
          run: bin/rails assets:precompile --trace

        - name: cache bundle.js
          uses: actions/cache@v3
          with:
            path: ./public/packs-test
            key: bundle-js-${{ github.sha }}

    - name: 'Compile webpacker assets'
      run: RAILS_ENV=test bundle exec rails webpacker:compile

    - name: 'Run RSpec Request Tests'
      run: bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/requests
