name: Rubocop

on: pull_request

jobs:
  rubocop:
    name: Rubocop test
    runs-on: ubuntu-18.04

    steps:
    - name: 'Checkout the repo'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: 'Set Ruby and Bundler Versions'
      run: |
        echo "RUBY_VERSION=3.0.4" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby and gems'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: 'Run Rubocop'
      run: bin/rubocop
