source 'https://rubygems.org'

gemspec

gem 'mysql2', '< 0.5x', '>= 0.3.13'

gem 'sortable-table', '~> 0.1'
gem 'stash-sword', path: '../stash-sword'

gem 'zaru', '~> 0.1'

group :development, :test do
  gem 'factory_bot_rails', require: false
  # gem 'factory_bot'
  gem 'rspec-rails'
end
